//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace turismo
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscripcion
    {
        public int id { get; set; }
        public int persona_id { get; set; }
        public int viaje_id { get; set; }
        public System.DateTime fecha_inscripcion { get; set; }
        public sbyte confirmado { get; set; }
        public Nullable<int> cantidad_pasajes { get; set; }
        public Nullable<int> monto { get; set; }
    
        public virtual viaje viaje { get; set; }
        public virtual persona persona { get; set; }
    }
}
