//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace turismo
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public persona()
        {
            this.inscripcion = new HashSet<inscripcion>();
            this.suscripcion = new HashSet<suscripcion>();
        }
    
        public int id { get; set; }
        public int rol_id { get; set; }
        public string nombre_usuario { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string token { get; set; }
    
        public virtual ICollection<inscripcion> inscripcion { get; set; }
        public virtual rol rol { get; set; }
        public virtual ICollection<suscripcion> suscripcion { get; set; }



        public string nombreUsuario { get; set; }
    }
}
