//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace turismo
{
    using System;
    using System.Collections.Generic;
    
    public partial class programa
    {
        public programa()
        {
            this.suscripcion = new HashSet<suscripcion>();
            this.viaje = new HashSet<viaje>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string imagen { get; set; }
    
        public virtual ICollection<suscripcion> suscripcion { get; set; }
        public virtual ICollection<viaje> viaje { get; set; }
    }
}
