//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace turismo
{
    using System;
    using System.Collections.Generic;
    
    public partial class suscripcion
    {
        public int id { get; set; }
        public int persona_id { get; set; }
        public int programa_id { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual programa programa { get; set; }
    }
}
