//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace turismo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class turismo_uvmEntities : DbContext
    {
        public turismo_uvmEntities()
            : base("name=turismo_uvmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<inscripcion> inscripcion { get; set; }
        public DbSet<pais> pais { get; set; }
        public DbSet<persona> persona { get; set; }
        public DbSet<programa> programa { get; set; }
        public DbSet<rol> rol { get; set; }
        public DbSet<suscripcion> suscripcion { get; set; }
        public DbSet<viaje> viaje { get; set; }
    }
}
