//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace turismo
{
    using System;
    using System.Collections.Generic;
    
    public partial class viaje
    {
        public viaje()
        {
            this.inscripcion = new HashSet<inscripcion>();
        }
    
        public int id { get; set; }
        public int programa_id { get; set; }
        public int pais_id { get; set; }
        public string descripcion { get; set; }
        public string titulo { get; set; }
        public string imagen { get; set; }
    
        public virtual ICollection<inscripcion> inscripcion { get; set; }
        public virtual pais pais { get; set; }
        public virtual programa programa { get; set; }
    }
}
